import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {useEffect} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    useEffect(()=> {
        console.log('test')
        fetch("https://vegemiska.pl/wp-json/wp/v2/posts")
            .then(response => response.json())
            .then(response=> {
                console.log(response)
            })
    }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1>
          Testowa strona 2
        </h1>

      </main>
    </>
  )
}
